# comment, don't touch it // never
#{0}{}{} //ever

// pseudo comment - don't touch them either
{633}{}{Да} // 1
{634}{}{Нет} // 2

//{2}{}{Быстрый} #skipped

{366}{}{Фанат бейсбола} // 4
{438}{}{Вы заблокировали доступ к терминалу.} // 6

{442}{}{и} // 10

{444}{}{Лифт занят.} // 12
{45}{}{вызвать лифт!} // 13